# Generated by Django 6.0.7 on 2026-07-08 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manzana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('dni', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('estado_legal', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADO', 'Ocupado'), ('REGULARIZANDO', 'En Regularización')], default='LIBRE', max_length=20)),
                ('estado_pago', models.CharField(choices=[('PAGADO', 'Pagado'), ('DEUDA', 'Con Deuda')], default='DEUDA', max_length=20)),
                ('coordenadas_mapa', models.JSONField(blank=True, null=True)),
                ('manzana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='gestion_lotes.manzana')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_lotes.propietario')),
            ],
        ),
    ]
